version: "3.8"


services:
  db:
    image: postgres:15
    container_name: todo-db
    restart: always
    environment: 
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    volumes:
      - ./backend:/app
    build: .
    container_name: todo-backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://todo_user:todo_password@db/todo_db

  pgadmin:
    image: dpage/pgadmin4
    container_name: todo-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: